name: Deploy Laravel to Shared Hosting

on:
  push:
    branches:
      - main # or your default branch

permissions:
  contents: write # allow pushing to repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history required to switch branches

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4" # Match your hosting PHP version

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Commit to build branch
        run: |
          git config user.name "github-action-build"
          git config user.email "tanzid3@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          # create or reset build branch from main
          git checkout -B build origin/main

          # remove vendor from gitignore in build branch
          sed -i '/\/vendor/d' .gitignore

          git add .gitignore
          git add vendor/ -f
          git commit -m "Build" || echo "No changes to commit"

          git push origin build --force
