name: Deploy Laravel to Shared Hosting

on:
  push:
    branches:
      - main # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history required to switch branches

      # 6️⃣ SSH into Hostiger and clear caches on live server
      - name: Deploy to Hostinger
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}   # or use private_key
          port: ${{secrets.HOSTINGER_PORT}}
          script: |
            cd ~/domains/artisanback.tanzid.site/public_html
            git pull origin main
            composer2 install --no-dev --optimize-autoloader
            php artisan view:clear
            php artisan cache:clear
            php artisan config:cache
